### ISSUE TITLE
Support feature branch deployments

### ISSUE THREAD

**Issue by gnadaban** [Food-X-Technologies/foodx_devops_tools#73]
**Is your feature request related to a problem? Please describe.**
Developers need to be able to deploy concurrently from a feature branch to validate their changes in a shared dev subscription without affecting others' resources.

This could potentially be solved by having an optional resource prefix parameter that would be empty string normally for dev, QA, staging and prod release states, and could be an arbitrary short string for feature branches or developer deployments.

Similarly to how `resource_suffix` is passed to resources via the `tags` parameter, an optional `resource_prefix` could be used to prefix resource group names when specified.

In feature branch deployments this prefix could be some hash generated from the branch name.

**Comment by blueskyjunkie** [comment]
resolved by https://github.com/Food-X-Technologies/foodx_devops_tools/pull/106
